[Triton-MLIR][HSACO] Added HSACO generation.
ROCmSoftwarePlatform/triton pull request #35
Opened 2022-11-28 22:42 UTC by dfukalov

The change is based on Rohit' commit 9bf807f310b19f6596526f84baf8bde46ff2dbd2

Used `AMDGCN_HSACO_DUMP_PATH=<dumpfile>` (example usage can be found in `tritongpu_to_hsaco.mlir` test) notion to save the copy of temp generated HSACO file. So a test is able to pass it to `llvm-readobj` and check its output.

2022-11-29 13:27 UTC, rsanthanam-amd commented on lib/Target/CMakeLists.txt
>  add_subdirectory(AMDGCN)
Since this PR already takes care of AMDGCN generation, please remove this subdirectory and references to it.

This was added in a previous commit.

2022-11-29 15:38 UTC, whchung commented on lib/Target/LLVMIR/LLVMIRTranslation.cpp
> +#include <iostream>
this header file is not really needed?

2022-11-29 15:40 UTC, whchung commented on lib/Target/HSACO/HSACOTranslation.cpp
> +  LLVMInitializeAMDGPUAsmPrinter();
Do we need `LLVMInitializeAMDGPUAsmParser()` here?

2022-11-29 15:42 UTC, whchung commented
Now #34 was just merged, perhaps this PR deserves a rebase to ensure no conflicts or mismatched functionalities.

2022-11-29 15:51 UTC, whchung commented on lib/Target/HSACO/HSACOTranslation.cpp
> +#include <iostream>
do we really need `regex`, `cstdio`, `iostream`? from the look of the PR these headers aren't really used.

2022-11-29 15:55 UTC, whchung commented on lib/Target/HSACO/HSACOTranslation.cpp
> +    std::cout << amdgcn << std::endl;
please use `raw_ostream` instead of `std::cout`.

2022-11-29 15:57 UTC, whchung commented on lib/Target/HSACO/HSACOTranslation.cpp
> +    std::cout << isabin_path << " was not created. error code: " << ec << std::endl;
please use `raw_ostream` instead of `std::cout`.

2022-11-29 15:57 UTC, whchung commented on lib/Target/HSACO/HSACOTranslation.cpp
> +    std::cout << "ld.lld execute fail: " << std::endl;
please use `raw_ostream` instead of `std::cout`.

2022-11-29 15:58 UTC, whchung requested changes
Please reuse `raw_ostream` instances already created by LLVM such as `llvm::outs` and `llvm::errs` for logging.

2022-11-29 19:06 UTC, dfukalov commented
> Now https://github.com/ROCmSoftwarePlatform/triton/pull/34 was just merged, perhaps this PR deserves a rebase to ensure no conflicts or mismatched functionalities.

@whchung the PR was actually merged in different branch. I'm agree that it conflicts with the changes, but suggest to resolve it with separate future step(s).

2022-11-29 19:06 UTC, dfukalov commented
> Since this PR already takes care of AMDGCN generation, please remove this subdirectory and references to it.
> This was added in a previous commit.
@rsanthanam-amd Thanks for this point, I missed it. But It seems we should actually use "AMDGCN" or "AMDGPU" name for the `Target` subfolder (since there is "PTX" but not "CUBIN". If you're agree, I'll merge new parts into "AMDGCN" subfolder.

2022-11-29 19:16 UTC, rsanthanam-amd commented
> > Since this PR already takes care of AMDGCN generation, please remove this subdirectory and references to it.
> > This was added in a previous commit.
> > @rsanthanam-amd Thanks for this point, I missed it. But It seems we should actually use "AMDGCN" or "AMDGPU" name for the `Target` subfolder (since there is "PTX" but not "CUBIN". If you're agree, I'll merge new parts into "AMDGCN" subfolder.

Yeah, i'm ok with your suggestion.

2022-11-29 20:37 UTC, rsanthanam-amd approved these changes

2022-11-29 20:38 UTC, rsanthanam-amd requested changes
Please address comments.

2022-11-30 05:08 UTC, rsanthanam-amd approved these changes
My comments have been addressed.

Waiting for Jack to approve before merging.

2022-11-30 14:13 UTC, whchung approved these changes

2022-11-30 14:19 UTC, merged