Add view_slice ttgir instruction
ROCmSoftwarePlatform/triton pull request #427
Opened 2023-12-13 22:10 UTC by oplavsic

This instruction represents view of the slice of the tensor in registers. Syntax of the operation is the same as for extract_slice op. However, unlike 'extract_slice' which slices in shared memory, 'view_slice' specifically slices within registers.
Slice of the tensor is required to have the same layout as the original tensor. In a way, semantics of the 'view_slice' operation is a combination of the 'extract_slice' and 'view' operations semantics.

This PR adds support for slicing tensors in blocked layout.
TODO: Support slicing in dot layout.

2023-12-13 22:13 UTC, oplavsic commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
> +   # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
Diff shows this graphical representation in a bad format. You can open the file to see it properly.
I can remove this representation if you think it's too much, but it should at least make review easier.

2023-12-13 22:15 UTC, oplavsic commented on include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
> +def TTG_ViewSliceOp : TTG_Op<"view_slice",
I retained syntax of the extract_slice operation, so this td description is (almost) the same as for extract_slice.

2023-12-15 14:32 UTC, zhanglx13 commented on include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
> +                                //  ResultsAreSharedEncoding,
I'm thinking if we want to add a trait to check that the slice and the parent tensor can have the same layout.

2023-12-15 14:36 UTC, zhanglx13 commented on include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
> +  }];
These are for `extract_slice` op. Just a note that when you actually use the `view_slice` op, you may want to have something different.

2023-12-15 14:53 UTC, zhanglx13 requested changes
The implementation seems good to me. However, there are mismatches for an untested config. See comment below.

2023-12-15 14:53 UTC, zhanglx13 commented on python/test/unit/language/test_core_amd.py
> +    %7 = tt.broadcast %6 : (tensor<1x{M}xi32, #src>) -> tensor<{M}x{M}xi32, #src>
Several places: {M}x{M} should be {M}x{N}

2023-12-15 14:53 UTC, zhanglx13 commented on python/test/unit/language/test_core_amd.py
> +@pytest.mark.parametrize("M, N, M_tile_size, N_tile_size, M_tile_offset, N_tile_offset", [[256, 256, 128, 64, 64, 128], [128, 128, 128, 32, 0, 0], [128, 128, 128, 32, 0, 64]])
I tried to add 
`[256, 128, 256, 32, 0, 0]`
And fixed all {M}x{M} issues in the IR, but there are mismatches for this config. Can you take a look?

2024-01-02 21:28 UTC, zhanglx13 approved these changes

2024-01-02 21:40 UTC, merged