Streamk v0.3
ROCmSoftwarePlatform/triton pull request #660
Opened 2024-11-06 21:25 UTC by xiaohuguo2023

streamk gemm script v0.3

- new persistent gemm kernel
- gemm benchmark tool using nearest neighbor approach.

2024-12-03 21:19 UTC, neoblizz requested changes
Looks good to me, my biggest comment here is I wonder if there's a way to merge streamk_kernel and streamk_kernel_atomic with some constexpr, so it uses the same code but uses atomics for the partials instead. That seems to be the fundamental change between the two but a bunch of redundant code is being used.

2024-12-03 21:19 UTC, neoblizz commented on python/perf-kernels/streamk/utils/gemm_wrapper.py
> +            #            STREAMK_TILES=total_tiles_streamk,
Shouldn't this be uncommented? Since all kernel signatures have `STREAMK_TILES` as a parameter?

2024-12-03 21:19 UTC, neoblizz commented on python/perf-kernels/streamk/README.md
> +# streamk gemm script v0.2
Is v0.2 relevant here? Or is this meant to be a changelog. If its not a changelog, and the features apply to both, consider moving the commands as a "Getting Started" or something for ease of use.

2024-12-03 21:19 UTC, neoblizz commented on python/perf-kernels/streamk/gemm_benchmark.py
> +    sm = 304
Might be worth removing hard-coded sm counts:

```py
import torch

if torch.cuda.is_available():
    current_device_index = torch.cuda.current_device()
    current_device = torch.cuda.get_device_properties(current_device_index)
    num_sms = current_device.multi_processor_count
```

2024-12-04 12:20 UTC, xiaohuguo2023 commented on python/perf-kernels/streamk/gemm_benchmark.py
> +    sm = 304
done, thanks

2024-12-04 12:21 UTC, xiaohuguo2023 commented on python/perf-kernels/streamk/README.md
> +# streamk gemm script v0.2
it is working like change log

2024-12-04 12:21 UTC, xiaohuguo2023 commented on python/perf-kernels/streamk/utils/gemm_wrapper.py
> +            #            STREAMK_TILES=total_tiles_streamk,
done, thanks

2024-12-04 16:14 UTC, xiaohuguo2023 commented
> Looks good to me, my biggest comment here is I wonder if there's a way to merge streamk_kernel and streamk_kernel_atomic with some constexpr, so it uses the same code but uses atomics for the partials instead. That seems to be the fundamental change between the two but a bunch of redundant code is being used.

the reason to put in atomics kernel here is for Ilia to test some accuracy issue of atomic_add, I would like to keep it separate for now just because we don't want to complicate the opt for our remainder part. We have next big task for reducing vgpr spills for the remainder.

2024-12-04 17:55 UTC, neoblizz approved these changes

2024-12-04 17:55 UTC, neoblizz commented
> > Looks good to me, my biggest comment here is I wonder if there's a way to merge streamk_kernel and streamk_kernel_atomic with some constexpr, so it uses the same code but uses atomics for the partials instead. That seems to be the fundamental change between the two but a bunch of redundant code is being used.
> 
> the reason to put in atomics kernel here is for Ilia to test some accuracy issue of atomic_add, I would like to keep it separate for now just because we don't want to complicate the opt for our remainder part. We have next big task for reducing vgpr spills for the remainder.

Looks good, thanks!

2024-12-04 20:37 UTC, zhanglx13 approved these changes

2024-12-04 20:37 UTC, merged