StreamK Grid Prediction Model
ROCmSoftwarePlatform/triton pull request #664
Opened 2024-11-15 00:26 UTC by ryanswann-amd

Implement Grid Model for StreamK which will predict the number of workgroups to launch for a given problem size.

2024-11-15 04:05 UTC, neoblizz requested changes

2024-11-15 04:05 UTC, neoblizz commented on python/perf-kernels/streamk/utils/grid_model.py
> +    # Fixed overhead alpha (a), fixed-size cost incurred by each work-group.
Missing comments for each constant.

```
 // Fixed overhead alpha (a), fixed-size cost incurred by
            // each work-group, e.g. the grid launch latency, the initial
            // compulsary cache misses, the cost of writing the final output tile
            // to C.
            double a = 5.04 + 8.30;

            // Beta (b) incorporates conditional costs of outputting temporary partial
            // sums for scenarios where the number of output tiles does not quantize
            // perfectly across the number of processors.
            double b = 5.47;

            // c represents instruction and stall workload of each MAC-iteration.
            double c = 4.17;

            // Delta (d) is the cost of reading and accumulating the partial sums from
            // other work-groups covering the same tile.
            double d = 18.59;
```

2024-11-15 19:08 UTC, neoblizz approved these changes

2024-11-19 19:57 UTC, merged

2024-11-19 20:00 UTC, ryanswann-amd commented
It was mentioned that I should provide a guide for the grid model. The goal of the grid model is to predict the number of CUs that StreamK should be launched on, as it may not always be optimal to launch streamk on all CUs at once. The top level function is:
```
def grid_model(
    m: int, #Problem Size M
    n: int, #Problem Size N
    k: int, #Problem Size K
    blk_m: int, #Block Size M
    blk_n: int, #Block Size N
    blk_k: int, #Block Size K
    grid_start: int = 1, #The minimum number of SM to predict
    grid_end: int = 304, #The maximum number of SM to predict
    verbose: bool = False,
) -> int:
```

You can use it like this:
```
from grid_model import grid_model

M = 2048
N = 2048
K = 2048
blk_m = 256
blk_n = 256
blk_k = 64

predicted_grid = grid_model(
    m=M, n=N, k=K, blk_m=blk_m, blk_n=blk_n, blk_k=blk_k, grid_start=1, grid_end=304
)
print(f"Predicted grid for {M}X{N}X{K} : {predicted_grid}")

```
In this case "predicted grid" captures a subset of cases where it may be more efficient to launch streamk on less than the total number of CUs. 
The use case for this would then be something like this:
```


```
predicted_grid=grid_model( m=M, n=N, k=K, blk_m=blk_m, blk_n=blk_n, blk_k=blk_k, grid_start=1, grid_end=304) #Get the predicted grid


streamk_gemm(M,N,K,blk_m,blk_n,blk_k,num_sm=predicted_grid.....) #use it when you launch streamk kernel
```