Fp8 fp16
ROCmSoftwarePlatform/triton pull request #80
Opened 2023-01-13 20:30 UTC by wenchenvincent

2023-01-13 20:34 UTC, rsanthanam-amd approved these changes

2023-01-13 20:41 UTC, rsanthanam-amd commented
@wenchenvincent please add test_f8_xf16_roundtrip to test_core_amd.py since it is passing with this PR.

2023-01-13 20:56 UTC, whchung requested changes
The title and the description need to be amended.

As an oblivious user with no background in fp8 I don't really understand what "fp8 fp16" means.

2023-01-13 21:56 UTC, wenchenvincent commented
> The title and the description need to be amended.
> 
> As an oblivious user with no background in fp8 I don't really understand what "fp8 fp16" means.

Sorry. Amended.

2023-01-14 14:13 UTC, rsanthanam-amd commented
@wenchenvincent please rebase this branch to pull in the latest changes from `triton-mlir`

2023-01-14 17:32 UTC, wenchenvincent commented
> @wenchenvincent please rebase this branch to pull in the latest changes from `triton-mlir`

Done.

2023-01-14 18:20 UTC, rsanthanam-amd commented
@wenchenvincent please move the added fp8 unit test up in test_core_amd.py to the same relative position that is it occurs in test_core.py.  This will facilitate cleaner diffs between test_core_amd.py and test_core.py.

2023-01-14 19:53 UTC, wenchenvincent commented
> @wenchenvincent please move the added fp8 unit test up in test_core_amd.py to the same relative position that it occurs in test_core.py. This will facilitate cleaner diffs between test_core_amd.py and test_core.py.

Done.

2023-01-14 20:42 UTC, merged

2023-01-14 20:43 UTC, rsanthanam-amd commented
Thanks!